### ISSUE TITLE
Given the Eigen implementation of SPE, do it with OpenCL

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#100]

**Comment by RobertLeahy** [comment]
@jordan-heemskerk: Looking at your branch `#130-workaround-jordan-edits`, specifically fb155d594ced9b519fe655d4981ebc104581c289 I see that some mathematical things in `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block` were changed.  These weren't reflected in the OpenCL kernel that we created on my branch `#100-opencl`, specifically as of 36a59a7c9ed03402ab6fd29f54756bb9a6792dc5.  Maybe this is important?

**Comment by RobertLeahy** [comment]
@jordan-heemskerk: I'm curious about what you're doing [here](https://github.com/RobertLeahy/DynFu/blob/fb155d594ced9b519fe655d4981ebc104581c289/src/kinect_fusion_eigen_pose_estimation_pipeline_block.cpp#L84).

`v_homo` and `pv_homo` are both homogeneous vectors.  We see [here](https://github.com/RobertLeahy/DynFu/blob/fb155d594ced9b519fe655d4981ebc104581c289/src/kinect_fusion_eigen_pose_estimation_pipeline_block.cpp#L57) and [here](https://github.com/RobertLeahy/DynFu/blob/fb155d594ced9b519fe655d4981ebc104581c289/src/kinect_fusion_eigen_pose_estimation_pipeline_block.cpp#L83) that their W component is 1.

[Matrix multiplication is distributive over addition.](http://mathworld.wolfram.com/MatrixMultiplication.html).  Therefore what you've written on that line is equivalent to: `t_z * (v_homo - pv_homo)`.  But the W components of both those vectors is guaranteed to be 1.  This means that the W component of `v_homo - pv_homo` is zero, which makes them equivalent to (after perspective division) [∞, ∞, ∞].

Is this really intended?  Am I misunderstanding it?

**Comment by jordan-heemskerk** [comment]
@RobertLeahy 

> I see that some mathematical things in dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block were changed. These weren't reflected in the OpenCL kernel that we created on my branch #100-opencl, specifically as of 36a59a7. Maybe this is important?

I did try this last, night, it's mostly just the extra multiplication by `t_z` and `r_z`. Didn't seem to change anything. Remember that they are both set to identity the first time its run too!

> v_homo and pv_homo are both homogeneous vectors. We see here and here that their W component is 1.
> 
> Matrix multiplication is distributive over addition.. Therefore what you've written on that line is equivalent to: t_z \* (v_homo - pv_homo). But the W components of both those vectors is guaranteed to be 1. This means that the W component of v_homo - pv_homo is zero, which makes them equivalent to (after perspective division) [∞, ∞, ∞].
> 
> Is this really intended? Am I misunderstanding it?

Yes, this is what is intended. First of all, we never actually do perspective division on the resultant vector, so the infinity case shouldn't be a concern. Instead, we are just taking `norm(v_homo-pv_homo)`. Since the w component is zero, it contributes nothing to the norm calculation, which is exactly what we want. We are looking for the distance between v_homo and p_homo in non-homogeneous space (ie, only the x,y,z components)
