### ISSUE TITLE
Verify kinect_fusion_opencl_update_reconstruction_pipeline_block

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#101]
Including the TSDF kernel in OpenCL

**Comment by JorinDW** [comment]
So questions are popping up. 
In src/test/kinect_fusion_opencl_update_reconstruction_pipeline_block.cpp
1. Should I use the kinect camera resolution values for K because that is what the rest of the system is calibrated for? Currently 16x16 from Jordan's original setup for the test. Are these specified for the hardware? Or do we specify them somewhere?
2. Does t_g_k need to be valid? Is it used throughout the background math for kfourpb.cpp? (can we even test this without t_g_k? Currently set to Identity

**Comment by JorinDW** [comment]
Going to try running tests without changing anything but the depth frame values first.

**Comment by RobertLeahy** [comment]
What is `kfourpb.cpp`?

**Comment by JorinDW** [comment]
shorthand for the full filename

**Comment by jordan-heemskerk** [comment]
1. No, this should depend highly on whatever depth values you make up to feed into it. The matrix has
   [fx, 0, px, 
   0 fy, py,
   0, 0, 1] where fx and fy are the x and y focal lengths and px py is the center coord of the frame. 
2. t_g_k must be set to some value, the natural "fake" value for it is the Identity, but you can specify it as any transformation matrix you like. It transforms voxels from the world space into the camera space.

**Comment by jordan-heemskerk** [comment]
1. cont'd if you look at the real K matrix in file_system_depth_device.cpp, you can see what the real Kinect camera one should be.

**Comment by JorinDW** [comment]
should we use the real values from the kinect camera for now? (do we have these?)
For fx, fy, px, py

**Comment by jordan-heemskerk** [comment]
Yes we have them, in the msrc_file_system_depth_device class somewhere...

I would only use those if you use real kinect camera depth measurements, as thats what it is calibrated for

**Comment by JorinDW** [comment]
Alright, I will move onto real depth values once the smoke/boundary/edge case testing is done and we know that it can handle the perfect stuff

**Comment by JorinDW** [comment]
Wondering how this results in something meaningful? (eg. x=0, y=0, z=0 gives element size = 0)
Why should the element size change?

https://github.com/RobertLeahy/DynFu/blob/test_tsdf/cl/tsdf.cl#L40

**Comment by jordan-heemskerk** [comment]
That looks like an error on my part. That should be the size in m of the elements. So the number of elements divided by the size dimensions of the volume.

??? Honestly I don't know but I agree it is incorrect.

**Comment by JorinDW** [comment]
Okay, I will look further into this.

**Comment by JorinDW** [comment]
Do you know where the total volume of the space is decided upon? I am looking for a hard coded value. I am wondering if that is something that should be passed into the kernel from a command line argument or something. Right now hard coding makes sense, but in the long run the ability to change the volume or abstract it away somehow makes sense possibly.

**Comment by JorinDW** [comment]
Could we get that from the dest array using a size operator? Is that pre-allocated?

**Comment by JorinDW** [comment]
Or can I use tsdf_width/height/depth?
