### ISSUE TITLE
Review Refactor of dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#126]
I made changes because I refactored `dynfu::pose_estimation_pipeline_block`, please make sure they're legitimate/alright.

Unit tests still pass.

See: ffc649ea766ff155da70d605b235a1454e992525

Note that you need to run `bin/tests` or `bin/tests.exe` (depending on platform) with the command line argument `[kinect_fusion_eigen_pose_estimation_pipeline_block]` as those tests now have `[!hide]` so they don't run as part of the standard suite and bog things down.

**Comment by jordan-heemskerk** [comment]
Note that we will start with an initial value for T_g_k, namely

```

                //needs to be a valid t_g_k for meaningful test (?)
                t_g_k = Eigen::Matrix4f::Identity();
                t_g_k(0,3) = 1.5f;
                t_g_k(1,3) = 1.5f;
                t_g_k(2,3) = 1.5f;
```

Thus, t_g_k should never be null when passed into the surface_prediction_pipeline_block. Hence, if the predicted V and N maps are null, we can just return the unmodified t_g_k that was passed in.

**Comment by RobertLeahy** [comment]
Upon further discussion: t_g_k can be null, we just need the `dynfu::pose_estimation_pipeline_block` to return the default value when it is.

This allows it to maintain control over creating the `dynfu::pipeline_value` objects that it deals in, which keeps things abstract.

**Comment by RobertLeahy** [comment]
See 82d3dc391ca7c37e0b24b887be80409225c284ec.
