### ISSUE TITLE
Name of "predicted" vertex/normal maps

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#128]
Implementing getters for the results of each frame on the `dynfu::kinect_fusion` class I'm not sure what to call the getter for the "predicted" vertex/normal maps (i.e. the output of the `dynfu::surface_prediction_pipeline_block`).

Right now I've named the functions [`predicted_vertex_map`](https://github.com/RobertLeahy/DynFu/blob/c482bbdaee517dbcb5b72a72112b43ca26002040/include/dynfu/kinect_fusion.hpp#L256) and [`predicted_normal_map`](https://github.com/RobertLeahy/DynFu/blob/c482bbdaee517dbcb5b72a72112b43ca26002040/include/dynfu/kinect_fusion.hpp#L269), but weren't we referring to them in conversation as "global vertex map" and "global normal map" at some point?  Should I change the names to `global_vertex_map` and `global_normal_map`?

See c482bbdaee517dbcb5b72a72112b43ca26002040.

**Comment by jordan-heemskerk** [comment]
No global is not quite right, predicted makes more sense
