### ISSUE TITLE
List of equipment required for the demo

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#129]
From #6:

> Loan of Equipment on the Public Presentation Day: Each team must send to the TA a list of
> equipment required for the demo three business days prior to the Public Presentation Day.
> This includes lab equipment, computers, monitors, internet access and facilities (such as:
> compressed air, water, outdoor setup, etc.)

**Comment by RobertLeahy** [comment]
The only things we should need (as far as I know, feel free to correct me) are one of the Macs from the lab and possibly the Kinect camera that we have in the lab (depends how we decide to go about the demo).

I assume taking that equipment out of the lab to use for our demo is okay, but perhaps we should consult with Andrea (avoiding tagging him unless we need/want to).

**Comment by JorinDW** [comment]
Email sent. Power, table, lab mac, and sensor.
