### ISSUE TITLE
OpenCL Pose Estimation Tests

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#136]
Test `dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block` in a similar manner to how we're testing `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block`.

**Comment by RobertLeahy** [comment]
Added a test to ensure that feeding in the same frame twice in a row gives a T_gk matrix which is simply the identity matrix (modulo the translation components provided in the matrix given to the constructor).

See 508c70e57192eef45f38ab3dfa750e4985fac801.

**Comment by RobertLeahy** [comment]
@jordan-heemskerk: Should we mark these test cases as `[!hide]` as we've done for the tests for `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block`?

**Comment by RobertLeahy** [comment]
Pretty trivial test to make sure it gives back `t_gk_initial` when invoked the first time.

See: abd96eb407161c07d3af07d8cc54cd439c44f6f2.

**Comment by RobertLeahy** [comment]
Here's an interesting test/alternative to the ["ground truth" used to test `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block`](https://github.com/RobertLeahy/DynFu/blob/8f2a2e6832740bb7c588b7bf17f533669e2eea07/src/test/kinect_fusion_eigen_pose_estimation_pipeline_block.cpp#L155): I simply [check the returned matrix to verify that it is a very small translation and a very small rotation](https://github.com/RobertLeahy/DynFu/blob/8f2a2e6832740bb7c588b7bf17f533669e2eea07/src/test/kinect_fusion_opencl_pose_estimation_pipeline_block.cpp#L193).

See: 8f2a2e6832740bb7c588b7bf17f533669e2eea07.

@jordan-heemskerk what do you think of this approach?  Suitable/appropriate?

**Comment by RobertLeahy** [comment]
Added a test for `dynfu::pose_estimation_pipeline_block::tracking_lost_error` like the one from [here](https://github.com/RobertLeahy/DynFu/blob/f84a70d0df6e6f65b63f9bf0ee51ebfdce487674/src/test/kinect_fusion_eigen_pose_estimation_pipeline_block.cpp#L167) but it fails.

GDB transcript:

```
(gdb) break src/kinect_fusion_opencl_pose_estimation_pipeline_block.cpp:184
Breakpoint 2 at 0x6d908866: file Z:\UVic\2016\Summer\SENG499\src\kinect_fusion_opencl_pose_estimation_pipeline_block.cpp, line 184.
(gdb) c
Continuing.

Breakpoint 2, dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block::operator() (this=0x22df90, v=..., n=..., prev_v=0x2d27e80, prev_n=0x2d2b4b0, k=...,
    t_gk_minus_one=std::unique_ptr<dynfu::pipeline_value<Eigen::Matrix<float, 4, 4, 0, 4, 4> >> containing 0x2d23e60) at Z:\UVic\2016\Summer\SENG499\src\kinec
184                             q_.enqueue_read_buffer(count_,0,sizeof(count),&count);
(gdb) n
185                             if (count>threshold) {
(gdb) print count
$1 = 252607
(gdb) print threshold
$2 = 276480
(gdb) print frame_height_*frame_width_
$3 = 307200
```

See: f84a70d0df6e6f65b63f9bf0ee51ebfdce487674.

@jordan-heemskerk: What (if anything) should we do about this?

**Comment by jordan-heemskerk** [comment]
> Should we mark these test cases as [!hide] as we've done for the tests for dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block?

No, they should be much quicker and should probably be tested every time we run the tests.

> what do you think of this approach? Suitable/appropriate?

It's pretty good. Ideally we would have some good ground truth values that we know are the absolute corect values to converge to, but since we don't, this should be fine for now I guess. Maybe open an issue to add ground truth testing to the `kinect_fusion_opencl_pose_estimation_pipeline_block`. Not sure that we'll ever get to it, but we will know it is missing.

> What (if anything) should we do about this?

We should decrease the threshold to make sure the test passes, ie. so that the `tracking_lost` exception is thrown.

**Comment by RobertLeahy** [comment]
> We should decrease the threshold to make sure the test passes, ie. so that the `tracking_lost` exception is thrown.

My issue with this is that under what I can tell is identical circumstances `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block` does throw, so what does this say about `dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block`?  Is it wrong?  Or is `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block` wrong?

**Comment by RobertLeahy** [comment]
As per @jordan-heemskerk looks like `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block` is still setup for frame-to-model tracking whereas `dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block` is setup for frame-to-frame tracking which could cause the differences we observed.

**Comment by RobertLeahy** [comment]
For the tracking lost test I switched from using frames 0 and 23 of "heads" to frames 0 and 238 which seems to get both `dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block` and `dynfu::kinect_fusion_eigen_pose_estimation_pipeline_block` to throw a `dynfu::pose_estimation_pipeline_block::tracking_lost_error`.

See: c4e9dd4840dd9f369300bb76e4aeb7eed4755a20.

**Comment by RobertLeahy** [comment]
> Ideally we would have some good ground truth values that we know are the absolute corect values to converge to, but since we don't, this should be fine for now I guess.

This is a good idea but I also think it's good to include this sort of test as a sort of from first principles sanity check on the generated matrix.
