### ISSUE TITLE
Create PRs and Merge Branches

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#140]
Right now we have the following issues in progress in a bunch of intertwined branches that we need to figure out how to merge:
#138, #136, #132, #130, #118, #100

**Comment by RobertLeahy** [comment]
We're considering merging `#100-opencl`, that has `#130-workaround` embedded in it.

**Comment by RobertLeahy** [comment]
`#100-opencl` also has `#118-demo` embedded in it.

**Comment by RobertLeahy** [comment]
Because we have separate branches we know that `#100-opencl` doesn't contain:
- `#138-save-mesh`
- `#132-cleanup`
- `#136-tests`

**Comment by RobertLeahy** [comment]
See #141.

**Comment by RobertLeahy** [comment]
@jordan-heemskerk; Can we delete `#130-workaround-jordan-edits` and/or `#100-jordan-experimentation`?

**Comment by jordan-heemskerk** [comment]
@RobertLeahy yea, I'll deal with it

**Comment by RobertLeahy** [comment]
All branches merged and issues closed.
