### ISSUE TITLE
Alternative to atomic_add to track correspondences (dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block)

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#145]
Andrea confirmed what I determined experimentally: [`atomic_add`](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/atomic_add.html) is bad for GPU performance.

We still need some way to track/check correspondences to make sure we maintain tracking.  Perhaps a second reduce step where we simply count the number of correspondences?

Andrea doesn't think that tracking/checking the number of correspondences when running the pipeline live is particularly important, so perhaps we need some way to turn the tracking/checking on and off.

**Comment by RobertLeahy** [comment]
A secondary reduce phase where NaNs are counted (and which is therefore easy to conditionally run) is a good idea imo.

**Comment by jordan-heemskerk** [comment]
We may not even need to track them. We can always just check the generated system for invertability, and then do a magnitude check on the returned delta-angles and delta-translations to determine if something went super wacky.
