### ISSUE TITLE
Rework the Pose estimation pipeline block to align with other kinfu paper

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#152]
http://research.microsoft.com/en-us/um/people/pkohli/papers/uist_2011.pdf

**Comment by jordan-heemskerk** [comment]
WHY ARE WE GETTING THIS 
![image](https://cloud.githubusercontent.com/assets/4603704/17011519/b8964698-4ec3-11e6-89d2-3ff8513e63c3.png)

**Comment by RobertLeahy** [comment]
60 frames:

![image](https://cloud.githubusercontent.com/assets/648276/17012401/37d15c74-4ecc-11e6-9b54-46a146ce597b.png)

**Comment by jordan-heemskerk** [comment]
120 frames:
![image](https://cloud.githubusercontent.com/assets/4603704/17012711/7288cce2-4ece-11e6-9445-fad9ac3aa897.png)

**Comment by jordan-heemskerk** [comment]
New scene 240 frames
![image](https://cloud.githubusercontent.com/assets/4603704/17013220/dcabd184-4ed1-11e6-869b-bce86cbda97f.png)

**Comment by jordan-heemskerk** [comment]
450 frames of heads
![image](https://cloud.githubusercontent.com/assets/4603704/17014102/85d48f9e-4ed7-11e6-825e-6a3241547107.png)

**Comment by jordan-heemskerk** [comment]
zipped .off file of above
[heads450.zip](https://github.com/RobertLeahy/DynFu/files/375319/heads450.zip)
