### ISSUE TITLE
Data "decaying" out of the TSDF

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#156]
As you can see here:

![Image of TSDF decaying](https://cloud.githubusercontent.com/assets/4603704/17014102/85d48f9e-4ed7-11e6-825e-6a3241547107.png)

While new data is being added old data (the first head and the first monitor) are decaying.

**Comment by jordan-heemskerk** [comment]
@RobertLeahy  This doesn't seem to be a problem anymore? I haven't reproduce this in a while, apart from the pose estimation going bonkers and causing some corruption.

**Comment by RobertLeahy** [comment]
I agree: We're not seeing this problem anymore.

I can't remember whether we actually changed the update reconstruction pipeline block, or if our changes/improvements to pose estimation fixed this, but either way I think we can close it.

We can always create another issue in the future if it happens again.
