### ISSUE TITLE
Improve performance of dynfu::kinect_fusion_opencl_pose_estimation_pipeline_block

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#157]
Right now is taking 4-8 seconds per frame.

This is clearly unacceptable.

We're not really sure why it's taking so long.  When we described our methodology/algorithm to Andrea he was surprised at how long it was taking as well.

**Comment by jordan-heemskerk** [comment]
Some light reading: http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/

**Comment by RobertLeahy** [comment]
From @jordan-heemskerk: http://http.developer.nvidia.com/GPUGems3/gpugems3_ch39.html

**Comment by RobertLeahy** [comment]
I've cleaned up & sped up the ICP/correspondences code (down to ~3ms per iteration on a full frame).

I implemented the parallel tree-based sum/reduce we talked about @jordan-heemskerk but it produces very slightly different answers from the previous sequential solution/implementation.

Parallel tree-based sum/reduce:

![image](https://cloud.githubusercontent.com/assets/648276/17078234/14a07d0c-50a2-11e6-9d5d-33af7b5bbb5a.png)

Sequential:

![image](https://cloud.githubusercontent.com/assets/648276/17078235/2ccbf154-50a2-11e6-85ca-a9b59642bb81.png)

Interestingly this causes no tests to fail.  In fact the test that exposed the `dynfu::kinect_fusion_opencl_measurement_pipeline_block` error/bug (see 700ee2eb633443014a96a5bb09ee4049b92db810) even still passes.  Printing the T_gk matrix gives:

```
  1   0   0 1.5
  0   1   0 1.5
  0   0   1 1.5
  0   0   0   1
```

So it's not just close enough for `isZero` or Catch's `Approx`, it's perfect.

For an idea on the kind of speed up we're talking about from this the sequential solution took ~100ms for the A matrix and ~100ms for the B matrix, so a total of ~200ms (per iteration) to reduce A & B.  The parallel tree-based solution is taking ~13ms (per iteration) for both.

To give you an idea on the kind of timeframes we're looking at with this in place:

![image](https://cloud.githubusercontent.com/assets/648276/17078282/75836412-50a3-11e6-8563-35340f777f87.png)

So we were about two orders of magnitude off, now it's about one.

**Comment by RobertLeahy** [comment]
Some low-hanging fruit that I think is obvious and which could give us "free" performance:
- Have the surface prediction and measurement pipeline blocks output "packed" vertex and normals.  I.e. instead of outputting two vectors in a tuple output one vector which has each point's vertex and normal packed into a 6 float struct.  Converting the input to this format takes the pose estimation pipeline block ~11ms.
- Pyramidal depth map (see #82).  This would reduce the size of the data set on many iterations.
