### ISSUE TITLE
Does the output of the Update Reconstruction processing block need to output the previous frame sensor pose estimation

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#16]

**Comment by jordan-heemskerk** [comment]
So I don't think the Update Reconstruction block needs to truly output the previous sensor pose estimation. However, the Surface Prediction block certainly takes the previous sensor pose as an input. So the question is, can a pipeline block have inputs that are not outputs from the previous block? If so, then there is no need for the Update Reconstruction block to output the previous sensor pose as it should have already been computed and saved in memory somewhere.

**Comment by RobertLeahy** [comment]
If you interpret "pipeline" strictly I think the next block's inputs must be exactly the outputs of the previous block, but we don't need to be that strict with it.

We have the class that manages everything: `kinect_fusion`, we can just have it store the values and pass them in/update them as needed.

Given that we haven't actually written any real code for `kinect_fusion` or any pipeline blocks, are you just critiquing/looking to update the documentation?

**Comment by jordan-heemskerk** [comment]
I think this question was left over from when we were brainstorming the pipeline blocks. So just looking forward... does the decision necessitate a documentation update?

Sounds like it's solved now though?

**Comment by RobertLeahy** [comment]
I dunno that it's "resolved" insamuch that I don't know that we know the answer to the originally posed question, but I don't think it particularly matters right now.

Having each pipeline block only accept the output of the previous block, given the way Kinect Fusion is laid out doesn't seem like a particularly elegant choice, so I always envisioned `kinect_fusion` as keeping all sorts of data lying around and updating/passing it as necessary.

**Comment by jordan-heemskerk** [comment]
The Update Reconstruction block definitely does not compute the previous sensor pose.  So in keeping with the envisioned `kinect_fusion`, the Update Reconstruction block should not output such an artifact.

I'd call that resolved now.
