### ISSUE TITLE
Switch solver types in dynfu::kinect_fusion_pose_estimation_pipeline_block

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#160]
We switched from column pivot to full pivot experimenting in 59f4d49f9f43c7e4dda99c44670a6ba4219aac78, should we switch back?  Or switch to something else entirely?

**Comment by jordan-heemskerk** [comment]
As per the [Princeton ICP derivation](http://www.cs.princeton.edu/~smr/papers/icpstability.pdf)

> The equation may be solved using standard methods (A is symmetric, so Cholesky decomposition is the preferred algorithm), yielding the optimal incremental rotation and translation

So I imagine we should switch to using a Cholesky factorization.
