### ISSUE TITLE
Normals - [NaN NaN NaN] vs. [0 0 0]

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#162]
`dynfu::kinect_fusion_opencl_measurement_pipeline_block` is producing both [0 0 0] (along the borders) and [NaN NaN NaN] (when any of the vertices it looks at is [NaN NaN NaN]).  Is there any difference in meaning/treatment or should we standardize around one?

Particularly I'm curious about how this interacts with [this](https://github.com/RobertLeahy/DynFu/blob/f444ea3d0cd22d389e1df96bdf5bf82ee851699e/cl/pose_estimation.cl#L78) since it's finite (whereas [NaN NaN NaN] isn't).

**Comment by jordan-heemskerk** [comment]
We should standardize one. I'll defer to you to choose a method, either is good by me

**Comment by RobertLeahy** [comment]
I'm thinking [NaN NaN NaN] since if accidentally misused it gives more obviously incorrect answers (you don't usually expect to see NaN).
