### ISSUE TITLE
Try to use OpenCL equivalent of Shader Memory

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#165]
CUDA would use shader memory to access things... can we figure out how to do this in Opencl

**Comment by RobertLeahy** [comment]
@ataiya would this be [`__local`](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/local.html) memory which we've been discussing/implementing/using as part of #179 and #157?

If so this issue is redundant and I can close it, if not I'm not really sure what it's for/about (it was one of the issues we created during our meeting on August 2nd) so if you could clarify that'd be great.

**Comment by taiya** [comment]
I don't know what the names are for OpenCL but in CUDA memory is organized in different layers (whose names there I also forgot). local, global (+texture) and shared if I am not mistaken. The per-thread memory (no inter-thread communication) is small but extremely efficient. That memory should be big enough for the accumulation step though (as far as Toby told us).

Is this what you have done above and gave you 4x speedup?

**Comment by RobertLeahy** [comment]
> The per-thread memory (no inter-thread communication) is small but extremely efficient.

I'm not sure what you mean by "thread".

In OpenCL terms "small but extremely efficient" sounds like it could only refer to [`__private`](https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/private.html) or [`__local`](https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/local.html).

The issue with `__private` is that it's not shared between work items as far as I can tell, whereas for the parallel sum we explicitly need this.

> Is this what you have done above and gave you 4x speedup?

Using `__local` memory as scratch space to perform the parallel sum and then only writing the final result to `__global` memory is what we did to gain the 4x speed up.  See 79f7e67938c4e452fbd3be44ca8a4e72f6c4f1fd.

**Comment by taiya** [comment]
CUDA Threads are quite extensively discussed online:
http://stackoverflow.com/questions/2392250/understanding-cuda-grid-dimensions-block-dimensions-and-threads-organization-s

It seems __local is exactly what I was referring to though (damn naming conventions!)

**Comment by RobertLeahy** [comment]
Given this I'm closing this issue as it is redundant given #179 and #157.

Further discussion (if necessary) should occur in #179.
