### ISSUE TITLE
Check OpenCL vs CUDA

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#174]

**Comment by RobertLeahy** [comment]
I found [this article](https://wiki.tiker.net/CudaVsOpenCL) (which claims there should be negligible performance differences between CUDA and OpenCL) which led me to this [repository/GitHub wiki](https://github.com/vetter/shoc/wiki/Results) which led me to this [Google Public Data Explorer](https://www.google.com/publicdata/explore?ds=bf0njpp5n6qjl_&ctype=b&strail=true&bcs=d&nselm=s&met_x=coreclock&scale_x=lin&ind_x=false&met_y=peakmembw&scale_y=lin&ind_y=false&idim=device:hd5750:hd5850:hd5870:hd5970:m2090:m2070ecc:c2050noecc:ion:gtx580:gtx570:gtx480:gtx470:gtx465:sb00:nehalem&ifdim=device&tunit=D&pit=1272772800000&icfg=bf0njpp5n6qjl_%253A23%253Adevice%26%26hd5750:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26hd5850:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26hd5870:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26hd5970:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26m2090:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26m2070ecc:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26c2050noecc:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26ion:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26gtx580:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26gtx570:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26gtx480:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26gtx470:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26gtx465:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26sb00:::2010-05-02%7Cbf0njpp5n6qjl_%253A23%253Adevice%26%26nehalem:::2010-05-02#!ctype=b&strail=true&bcs=d&nselm=s&met_y=s3d&fdim_y=platform:cuda50&scale_y=lin&ind_y=false&met_x=s3d&fdim_x=platform:nvocl50&scale_x=lin&ind_x=false&idim=device:hd5750:hd5850:hd5870:hd5970:m2090:m2070ecc:c2050noecc:ion:gtx580:gtx570:gtx480:gtx470:gtx465:sb00:nehalem:gtx690:gtx680:hd7970:hd5770:hd5670:llano:c1060&ifdim=device&pit=1272772800000&hl=en_US&dl=en_US&ind=false) which provides data which supports the assertion that OpenCL vs. CUDA performance difference is negligible (with OpenCL even coming out ahead of CUDA on nVidia hardware for the majority of those data points).  I will grant that the cards for which data is available here are old (3 generations old is the newest as far as I can tell).

I'm going to go ahead and close this issue.  If @ataiya wants to see more data/investigation feel free to comment and I'll reopen.
