### ISSUE TITLE
Rename Repository and Make it Public

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#184]
As per @ataiya:

> Rename repo as "kinfu" and make it public
> 
> Or Toby won't be able to see the code
> Thanks --Andrea

Should we also change the namespace to `kinfu` from `dynfu` or does that not matter?

**Comment by jordan-heemskerk** [comment]
If we change the repo name, we should probably change the namespace

**Comment by taiya** [comment]
I guess, it's one regex in a text editor, not much work :)
