### ISSUE TITLE
Benchmark All Pipeline Blocks

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#219]
Right now we don't call [`clFinish`](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clFinish.html) at the end of each pipeline block which means that jobs may still be running on the GPU as we proceed to the next block.

Under ordinary circumstances we'd want this (there's no reason to not have the CPU move on while the GPU is busy) but for benchmarking it's important we're not letting the time elapsed for one block "bleed" into the next.

Accordingly we should add `clFinish` calls to the end of each pipeline block and generate benchmarking figures that way, just so we know exactly where all our time is going.

**Comment by RobertLeahy** [comment]
Results with TSDF size of 256 on my PC:

| Pipeline Block | Time | Percentage of Frame |
| --- | --- | --- |
| Depth Frame | 0 ms | 0% |
| Measurement | 4 ms | 8.7% |
| Pose Estimation | 10 ms | 21.7% |
| Update Reconstruction | 12 ms | 26.1% |
| Surface Prediction | 19 ms | 41.3% |
| Overhead | 1 ms | 2.2% |
| Total | 46 ms | 100% |

46 ms translates to ~21.74 frames per second which means we still have to improve running time by ~27.5% to reach our target of 30 frames per second.

We also need to benchmark capturing frames from the actual Kinect camera, since currently we're using [`dynfu::buffered_depth_device`](https://github.com/RobertLeahy/DynFu/blob/cc37b928da14630527ce8f134988c474bc2ed0bd/include/dynfu/buffered_depth_device.hpp) loading from the filesystem which has little-to-no overhead since everything is handled by a background thread.

So @jordan-heemskerk's decision to optimize surface prediction in #218 seems well founded.

**Comment by RobertLeahy** [comment]
Results with a TSDF size of 512 on my PC:

| Pipeline Block | Time | Increase over 256 TSDF size | Percentage of Frame |
| --- | --- | --- | --- |
| Depth Frame | 0 ms | 0% | 0% |
| Measurement | 4 ms | 0% | 3.4% |
| Pose Estimation | 10 ms | 0% | 8.5% |
| Update Reconstruction | 88 ms | 633.3% | 74.6% |
| Surface Prediction | 15 ms | -21.1% | 12.7% |
| Overhead | 1 ms | 0% | 0.8% |
| Total | 118 ms | 156.5% | 100% |

Interesting that surface prediction time decreases.

**Comment by jordan-heemskerk** [comment]
According to the Kinect Fusion paper, the 633% speedup is to be expected when running with the larger TSDF. Although the paper does not give actual values (only a graph) it can be ascertained that at 256^3 resolution, the Update Reconstruction takes about 1-2ms, while at 512^3 resolution the value jumps to ~15ms.

This leads me to believe that there are some optimisations that can be applied to the Update Reconstruction block still as well.

**Comment by RobertLeahy** [comment]
Conclusions:
- Surface prediction must be optimized (see #218)
- Update reconstruction must be optimized (issue forthcoming)
- [`dynfu::opencv_depth_device`](https://github.com/RobertLeahy/DynFu/blob/aadfb873d51b46c84dc57803ff25cc4ab4049086/include/dynfu/opencv_depth_device.hpp) must be benchmarked (see #220)

**Comment by RobertLeahy** [comment]
For code used to generate these benchmarks see 4354423a6e7df3a187948fb467f77e67a2852349.
