### ISSUE TITLE
Code to do benchmarking

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#36]
I remember you had this idea, probably another good thing to track so we don't forget :)

**Comment by RobertLeahy** [comment]
See fb108f8 & feab37b.

**Comment by RobertLeahy** [comment]
See 81c6703e2413f85d84acae3f105bb94df73a728d, 4e3b7a068dcc3aeac58612a08c7bdf6d5fb3ac49, & caf20967093e90b861f4f0d126917699d64ae24a.
