### ISSUE TITLE
Change seng499 namespace to dynfu and rename repo

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#42]

**Comment by RobertLeahy** [comment]
Are we going to use `dynfu` or `dyn_fu` for the namespace?  I think the former is better but I don't want to take action without consensus.

I'll go ahead and rename the repository.

**Comment by jordan-heemskerk** [comment]
dynfu

**Comment by RobertLeahy** [comment]
I renamed the repo to "DynFu", I assume that capitalization is correct/desired?

**Comment by jordan-heemskerk** [comment]
:+1:
