### ISSUE TITLE
Support loaner cameras

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#47]

**Comment by RobertLeahy** [comment]
Can't seem to make any of the APIs for accessing this camera play nice with MinGW GCC.

Tried using Windows Media Foundation and the number of linker errors and missing signatures in headers was just too overwhelming.

Right now we should be good with the MSRC datasets, so just kicking this can down the road it's not worth dealing with right now.

**Comment by taiya** [comment]
Given most of you are working in linux/osx I'd say the best pick would be to use the Kinect camera (OpenNI drivers). I have it in my office, you can pass by to sign it out. It'd be the same hardware used to generate the MSR datasets.

**Comment by jordan-heemskerk** [comment]
@RobertLeahy should we close this and open a new issue for supporting OpenNI? I don't see us getting the Intel sensors going...

**Comment by RobertLeahy** [comment]
Maybe we should figure out some way to mark an issue as a possible, optional long-term enhancement?

Or should we just return the sensors to @ataiya?

**Comment by jordan-heemskerk** [comment]
I've already boxed mine up :P

**Comment by RobertLeahy** [comment]
We have an issue for OpenNI (#76).

**Comment by RobertLeahy** [comment]
Removed "help wanted" label and leaving this open in case we want to support these in the long-term (see: Milestone).

If we wind up returning the cameras to @ataiya we'll close this issue.

**Comment by taiya** [comment]
I guess the core issue is the lack of USB3 support on the iMacs?
I thought you guys had gaming machines with USB3 at home though.
Anyway, your pick.

**Comment by RobertLeahy** [comment]
I tried getting setup on my machine at home, but the Intel SDK to interface with the camera seemed to want MSVC, which is a road I'd rather not go down.

The camera was picked up by Windows & Skype as a webcam (both RGB and depth were picked up as separate devices) so I thought maybe I'd used Windows Media Foundation to pull depth frames that way, but the headers I had access to were woefully incomplete (missing a lot of core Windows Media Foundation functions et cetera) and I got so many linking errors that I decided it wasn't worth the time investment and gave up.

**Comment by RobertLeahy** [comment]
This is never going to happen.
