### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#53]
Let's see if we can't fix the `{#mainpage}` thing (Doxygen artifact).

Update dependencies (OpenCV, Boost, and Boost.Compute are all missing).

**Comment by jordan-heemskerk** [comment]
Remove the waffle badge, its not working with the private repo

**Comment by RobertLeahy** [comment]
Also: The directions in `README.md` are out of date because we're using CMake now (see #67).

When writing new directions `.travis.yml` will probably be instructive as it has to setup the build environment on Travis from nothing.

**Comment by RobertLeahy** [comment]
Also the notes I've left getting setup building on the Macs in the lab (see #69) will probably be helpful.

**Comment by RobertLeahy** [comment]
I'm taking over this issue for the Windows update as per discussion in #80.
