### ISSUE TITLE
Adjust OpenCL kernels to be more sensitive to qNaN

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#54]
qNaN signals a bad depth measurement, the kernels need to treat these with higher regard to prevent erroneous results.

**Comment by RobertLeahy** [comment]
Will branching on checking if a value in NaN on every pixel input (and then every subsequent input since those NaNs will be carried through) wreck our performance?

**Comment by RobertLeahy** [comment]
Once we do implement some respectful process for handling NaNs be sure to unit test with NaN inputs.

**Comment by jordan-heemskerk** [comment]
The Kinect Fusion paper uses a vertex validity map called M_k where 1 indicates a valid depth measurement and 0 indicates an invalid depth measurement.

**Comment by RobertLeahy** [comment]
Another way to handle this is to operate under the assumption that all depth measurements could possibly return finite values and just ignore NaN (i.e. not special case it) and treat it as any other value.

For example: The sensor may be measuring a surface which is a certain material or at a certain angle such that it does not register.  This is NaN in the data but in reality there is a finite associated depth.

Another example: The time of flight is too long because the measured depth is out of range.

In both these cases NaN is a stand in for some finite value.  So if we just ignore NaNs and treat them as if they were any other value then the only instance in which they become non-NaN is where any real value would produce the same result: I.e. the result is the same as if we had the actual depth, so it doesn't matter.

[See here.](http://www.gnu.org/software/libc/manual/html_node/Infinity-and-NaN.html)

**Comment by RobertLeahy** [comment]
We also discussed treating NaN as Inf, but there's a problem here in that Inf is deliberately and explicitly non-finite whereas depth values are logically always finite even if very large (it is exceedingly unlikely that a depth measurement actually sails off to **true** infinity).

**Comment by jordan-heemskerk** [comment]
An entirely different point of view is that the high frame rate of Kinect Fusion allows for the filtering of outlying vertices and therefore if we assume that we will encounter only a small  number of NaNs then they should be filtered out by the TSDF averaging.

**Comment by RobertLeahy** [comment]
@ataiya, do you have any insight into/advice on this?

**Comment by taiya** [comment]
I'd use an #ifdef that allows you to swap between NaN and a small value (closer than the "near" clipping plane) according to whether you are debugging or running in release. Very small detail overall.

**Comment by RobertLeahy** [comment]
@jordan-heemskerk what's the status on this?  Can we close this issue or is there work to be done?

**Comment by jordan-heemskerk** [comment]
This can be closed.
