### ISSUE TITLE
Measurement block invalid normals along edges

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#57]
Perhaps talk to Andrea?

**Comment by RobertLeahy** [comment]
@ataiya, @jordan-heemskerk and I noticed when implementing the measurement block that the normals along two of the edges of each frame are the null vector [0 0 0] due to the way the filter/mask works.  How should we deal with this?  Should we detect the boundary cases and respond accordingly, ignore it and let it average out as frames accumulate, et cetera?

**Comment by taiya** [comment]
Not sure I fully understand the issue.
Let's clarify in person (see my email soon).

**Comment by jordan-heemskerk** [comment]
@ataiya says that we can just ignore these values as they will be filtered out in the registration due to a high deviation of the normal

**Comment by taiya** [comment]
Careful, there were 2 different issues:

1) sudden discontinuities in depth: this is where the normal _should_ be almost orthogonal to the view-ray and therefore the confidence weight you compute should be \approx 0.
2) image boundary - just ignore those pixels, you are tossing only O(n) over O(n^2) pixels, it's negligible.
