### ISSUE TITLE
Client/Example program

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#58]
We're going to want some way to "test" our implementation with more than just unit testing to make sure that it makes sense/produces good results.

We also want something to demo.

Create a C++ client program that consumes the DynFu shared library and does something interesting/processes an interesting dataset.

Whether we use actual camera or MSRC datasets shouldn't matter/should depend on our needs.

**Comment by RobertLeahy** [comment]
We have a partial implementation (one that consumes everything we've implemented to this point) as of 76d2b46.

Since the implementation is partial, and since it'll have to wait on other features being implemented to advance itself, I'm marking this issue ongoing and moving it to long-term: We'll have to keep working on the client/example program/front-end as we go.

**Comment by JorinDW** [comment]
I am going to start thinking about a way for us to demo. This was one take-away from our previous project together, that the demo matters. I will note progress and take notes and post here.

**Comment by jordan-heemskerk** [comment]
Track in #118 instead

**Comment by jordan-heemskerk** [comment]
Track in #118 instead
