### ISSUE TITLE
Questions process

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#59]
Talk to Andrea and figure out what process he wants observed for questions we have for him.

Right now we have the following three processes to suggest:
1. Assign GitHub issues to him
2. Make a thread in the Google Groups
3. Wait until next in person meeting and bring them to him then

The only issue I see with #3 is that some of these issue have a lot of discussion in them and him having to filter through them while we're there could waste time or create unnecessary pressure.

**Comment by taiya** [comment]
You can mention me in discussion with @ataiya and I will receive a notification. I'll turn off "watch repository" as I received 35 emails just for today :)
