### ISSUE TITLE
Public Presentation

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#6]
Project demonstrations and presentation will be made to the Faculty and University
community and the general public. Each team will be provided with a 6’x 4’table for the
demo and display of the prototype in the ELW Lobby (to be booked from 1:00 pm on the day
of the demo).
Each display should include the names of the team members, the project supervisor and the
sponsor (if applicable). Team members are expected to be present during demonstrations and
presentation to answer questions and offer explanations to relevant queries from the
attendees. In addition, each team is required to prepare pamphlets to be given out. The design
should be similar to that of a commercial product.
The event is sponsored by the IEEE Victoria Section and co-sponsored by other
organizations with cash prices for the best projects.
Loan of Equipment on the Public Presentation Day: Each team must send to the TA a list of
equipment required for the demo three business days prior to the Public Presentation Day.
This includes lab equipment, computers, monitors, internet access and facilities (such as:
compressed air, water, outdoor setup, etc.)

**Comment by RobertLeahy** [comment]
See #118.

**Comment by RobertLeahy** [comment]
Good code to run at the demo is tagged with `demo`.
