### ISSUE TITLE
What're good values for sigma S and sigma R?

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#63]
These values are used by `dynfu::kinect_fusion_opencl_measurement_pipeline_block`.

**Comment by RobertLeahy** [comment]
@ataiya, these are parameters to the [bilateral filter](https://users.cs.duke.edu/~tomasi/papers/tomasi/tomasiIccv98.pdf) used by the measurement block.

@jordan-heemskerk thought you'd have an idea of values to use for these as a baseline/default.

**Comment by jordan-heemskerk** [comment]
~~In computer vision we used the one ring neighborhood of pixels, also called the 8-neighblourhood when we don't need too much accuracy, that might be good enough for our application.~~

EDIT: This was the wrong issue

**Comment by taiya** [comment]
I don't see a question?
[edit] Right, but I don't know what those symbols exactly refer to (note you can upload screenshots to github issues)

**Comment by RobertLeahy** [comment]
The question is in the title of the issue: What are good starting values for these?

**Comment by RobertLeahy** [comment]
As per @jordan-heemskerk and #64 once we figure this out we should use those values to calculate the size of the bilateral filter's window.

**Comment by RobertLeahy** [comment]
Talked to Andrea: Arbitrary, tweak until happy. Check KinFu/PCL.

**Comment by jordan-heemskerk** [comment]
@4444jw4444 can you look in the PCL implementation and find what their default values for sigma s and sigma r are and comment them here?

**Comment by jordan-heemskerk** [comment]
Transferring to @helenroy.

Sigma_s and Sigma_r are in Eqn 2

**Comment by jordan-heemskerk** [comment]
const float sigma_color = 30;     //in mm
    const float sigma_space = 4.5;     // in pixels
