### ISSUE TITLE
What's a good size for the bilateral filter's window?

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#64]
Bilateral filter window support added in 25d2c17.  What's a good value for it/what should it default to?

**Comment by RobertLeahy** [comment]
@ataiya same as #63 except the number of pixels to the left/right/top/bottom of the current pixel that should be considered when filtering.

Right now I'm using 20, but I'm not sure if that's ideal.

We were using all pixels, but that was traumatically slow (>1.5s per frame).

**Comment by jordan-heemskerk** [comment]
From [here](http://stackoverflow.com/questions/16165666/how-to-determine-the-window-size-of-a-gaussian-filter).

> To this respect, as I already said, you can choose a mask with a size which is generally three times the standard deviation.

**Comment by RobertLeahy** [comment]
The standard deviation of what?  Each frame?

**Comment by jordan-heemskerk** [comment]
The standard deviation of the filter (ie. sigma_s and sigma_r)

**Comment by taiya** [comment]
Bilateral filters use a compactly supported weight function. Therefore, you just need to make sure the weight function is ~0 on the border of your window (choose a value, then reverse engineer the window size).

**Comment by jordan-heemskerk** [comment]
Sounds good. I think we can close this, as it can be directly calculated once #63 is resolved.
