### ISSUE TITLE
Build System Overhaul

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#67]
1. Support Mac OSX (lab machines)
2. Revamp current build system (either better/cleaner makefile, or something else entirely)

**Comment by jordan-heemskerk** [comment]
Can we make it so clean doesn't ditch the OpenCV DLLs on Windows that may be in the bin dir

**Comment by RobertLeahy** [comment]
If we do that then `make clean` won't remove `bin`, but `bin` is a build artifact, so then `make clean` won't really make the directory clean.

This is something we can discuss.  If people want the OpenCV DLLs kept that badly I can do it.

**Comment by jordan-heemskerk** [comment]
ya probs best not to do it and install the DLLs properly.

**Comment by RobertLeahy** [comment]
The meaning of "properly" is kind of unclear on Windows though: By default the Windows loader searches the path of the executable alongside system paths, so arguably just putting the OpenCV DLLs in the same directory as the executable **is** properly installing them.

**Comment by RobertLeahy** [comment]
With respect to point 2 (revamping the build system and possibly switching build system) @jordan-heemskerk and I have identified three options:
1. Continuing with [GNU Make](https://www.gnu.org/software/make/)
2. Switching to [CMake](https://cmake.org/)
3. Switching to [Boost.Build](http://www.boost.org/build/)

**Comment by RobertLeahy** [comment]
I implemented a CMake-based build system.
