### ISSUE TITLE
Find out how to have additional pages in Doxygen

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#73]
Then document non code artifacts, such as what a TSDF is and link to throughout the docs.

**Comment by JorinDW** [comment]
[here](http://stackoverflow.com/questions/3052036/how-to-include-custom-files-in-doxygen) is how we can do this hopefully.
[here](http://stackoverflow.com/questions/9502426/how-to-make-an-introduction-page-with-doxygen) is how we can do an introductory page on the website. 
I'll get to work on this.
