### ISSUE TITLE
Research & Integrate OpenNI

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#76]
Andrea mentioned this as a way to get the Kinect sensor running on/working with non-Windows platforms.

**Comment by jordan-heemskerk** [comment]
Steal Andrea's work here: https://github.com/OpenGP/htrack/blob/master/tracker/Sensor/Sensor_openni.cpp heheh

**Comment by RobertLeahy** [comment]
I've been fooling around with this [fork of OpenNI2](https://github.com/occipital/OpenNI2).  A link to it might be handy to have for reference.

**Comment by jordan-heemskerk** [comment]
Since we already have a dependency on OpenCV, this might be useful http://docs.opencv.org/2.4/doc/user_guide/ug_kinect.html

**Comment by RobertLeahy** [comment]
Currently the OpenCV dependency is only for the file system depth map sources, and isn't really a dependency insamuch that it's not needed except for testing.

Are we content to make it a real, hard dependency?  If so we can look into this.

**Comment by jordan-heemskerk** [comment]
If it cuts down on dev time, might be worth it. Otherwise roll our own with true OpenNI

**Comment by RobertLeahy** [comment]
Installing OpenNI2 using steps found [here](https://github.com/totakke/homebrew-openni2).

**Comment by RobertLeahy** [comment]
Looking [here](https://github.com/occipital/OpenNI2/issues/47) for help on how to build OpenCV with OpenNI2 support, doesn't seem to be helping...

**Comment by RobertLeahy** [comment]
Looking in the OpenCV source, under `cmake/OpenCVFindOpenNi2.cmake`:

```
# Main variables:
# OPENNI2_LIBRARY and OPENNI2_INCLUDES to link OpenCV modules with OpenNI2
# HAVE_OPENNI2 for conditional compilation OpenCV with/without OpenNI2
```

**Comment by RobertLeahy** [comment]
`cmake -D OPENNI2_LIBRARY=/usr/local/lib/ni2/libOpenNI2.dylib -D OPENNI2_INCLUDES=$OPENNI2_INCLUDE -D WITH_OPENNI2=ON .`

**Comment by RobertLeahy** [comment]
`cmake -D OPENNI2_LIBRARY=/usr/local/lib/ni2/libOpenNI2.dylib -D OPENNI2_INCLUDES=/usr/local/include/ni2 -D WITH_OPENNI2=ON .`

**Comment by RobertLeahy** [comment]
Doesn't seem to be finding the OpenNI2 include files (complaining about `OpenNI.h`) even though I've confirmed that file is present at the include directory I've given.

**Comment by RobertLeahy** [comment]
`cmake -D OPENNI2_LIBRARY=/usr/local/lib/ni2/libOpenNI2.dylib -D OPENNI2_INCLUDES=/usr/local/include/ni2 -D WITH_OPENNI2=ON -D OPENNI2_LIB_DIR=/usr/local/lib/ni2 -D OPENNI2_INCLUDE_DIR=/usr/local/include/ni2 .`

**Comment by RobertLeahy** [comment]
Command in previous comment seemed to work.  Followed it up with `make` and then `make install`.  Now getting the following error when running the unit tests:

```
/Users/dynfu/Documents/DynFu/src/test/opencv_depth_device.cpp:11: FAILED:
  CHECK_NOTHROW( dynfu::opencv_depth_device{} )
due to unexpected exception with message:
  /Users/dynfu/Documents/OpenCV-3.1.0/opencv-3.1.0/modules/videoio/src
  /cap_openni2.cpp:379: error: (-2) CvCapture_OpenNI2::readCamerasParams :
  Could not read virtual plane distance!
   in function readCamerasParams
```

**Comment by RobertLeahy** [comment]
Had to actually patch OpenCV.

[This line](https://github.com/opencv/opencv/blob/f9e674180708a26ad05865040ec09f87a0d5edfa/modules/videoio/src/cap_openni2.cpp#L405) change the type to `long long`.

Got the idea from [here](http://stackoverflow.com/a/34690264/1007504).

**Comment by RobertLeahy** [comment]
Here's the full dump I was getting:

```
OpenNI2-FreenectDriver: Using libfreenect v0.4.1
OpenNI2-FreenectDriver: Found device freenect://0
OpenNI2-FreenectDriver: Opening device freenect://0
write_register: 0x0105 <= 0x00
write_register: 0x0006 <= 0x00
write_register: 0x0012 <= 0x03
write_register: 0x0013 <= 0x01
write_register: 0x0014 <= 0x1e
write_register: 0x0006 <= 0x02
write_register: 0x0017 <= 0x00
write_register: 0x000c <= 0x00
write_register: 0x000d <= 0x01
write_register: 0x000e <= 0x1e
write_register: 0x0005 <= 0x01
write_register: 0x0047 <= 0x00
OpenNI2-FreenectDriver: (ERROR) Unexpected size for XN_STREAM_PROPERTY_ZERO_PLANE_DISTANCE
OpenCV Error: Unspecified error (CvCapture_OpenNI2::readCamerasParams : Could not read virtual plane distance!
) in readCamerasParams, file /Users/dynfu/Documents/OpenCV-3.1.0/opencv-3.1.0/modules/videoio/src/cap_openni2.cpp, line 379
write_register: 0x0005 <= 0x00
[Stream 70] Expected max 1748 data bytes, but got 1908. Dropping...
[Stream 70] Invalid magic 0300
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 0680
[Stream 70] Invalid magic 3f37
[Stream 70] Lost 9 packets
[Stream 70] Lost 9 total packets in 2 frames (4.500000 lppf)
[Stream 70] Lost too many packets, resyncing...
write_register: 0x0006 <= 0x00
OpenNI2-FreenectDriver: Closing device freenect://0
```

**Comment by RobertLeahy** [comment]
[This documentation will probably be useful.](http://docs.opencv.org/3.1.0/d8/dfe/classcv_1_1VideoCapture.html)

**Comment by RobertLeahy** [comment]
[Also this.](http://docs.opencv.org/2.4/doc/user_guide/ug_kinect.html)
