### ISSUE TITLE
Travis Build Failed

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#77]
[This Travis build failed](https://travis-ci.com/RobertLeahy/DynFu/jobs/41155485), but the GCC 6.x build which ran right after it succeeded.

I assume this is random?  Is there anything we can do to prevent/control this?

**Comment by jordan-heemskerk** [comment]
Looks like a random failure...

You can always manually restart the build if you think something weird is going on. See this screenshot.
![image](https://cloud.githubusercontent.com/assets/4603704/15630906/b0997508-2503-11e6-82af-8aaddd487c2c.png)

I restarted the aforementioned build and it succeeded this time.
