### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#8]
A final report is required for each project. It should be typewritten, bound and organized
according to the following format:
i. Project Title
ii. Executive Summary – A brief overview of the project goal, description of the project
and the final design, performance and recommendations/modification and future
work. Do not exceed one page.
iii. Introduction – Includes motivation, objectives, review of existing solutions and
alternative designs, deliverables and technical specifications.
iv. Detailed Design Description – Provides a comprehensive description of the full
design and the prototype. Include a detailed description of the testing of the
prototype, performance and results, discussions and impact of the results on the
design process, recommendations and limitations. Tables and figures can be added
for illustration.
v. Project and team Management – Provides a detailed breakdown of the tasks and
scheduled responsibility completed by the individual team members. 6) Conclusions
and Recommendations – Provides a clear and concise summary that summarises the
outcome. Suggests possible improvements and/or future work.
vi. Include a section on references
vii. Appendix – add Cost Analysis and Parts List. Use tables to provide detailed cost and
source information.
viii. Other Appendix (if applicable)
The final report must be submitted on the required deadline date to the project Supervisor
and TA for evaluation. It will not be returned to the team after evaluation.

**Comment by RobertLeahy** [comment]
@jordan-heemskerk and I have decided that we definitely want to feature our workflow/process in the final report (and perhaps the pamphlet?  See #113).

Accordingly we're going to want to see a detailed description/discussion of our process including (but not limited to):
- [Pull requests](https://github.com/RobertLeahy/DynFu/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged) and the code review (for example: #103) that goes along with them
- GitHub issues, tags, and [Waffle](https://waffle.io/RobertLeahy/DynFu)
- [Unit testing](https://github.com/RobertLeahy/DynFu/tree/master/src/test)/[Catch](https://github.com/philsquared/Catch)
- [Continuous integration](https://travis-ci.com/RobertLeahy/DynFu)
- [Documentation/Doxygen](http://dynfu.rleahy.ca/)
