### ISSUE TITLE
SSH access to Mac(s) in the labs

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#86]
See if we can't get SSH access to the Mac(s) in the labs, would greatly aid in testing/development and support of Mac OSX as a platform.

**Comment by RobertLeahy** [comment]
Macs appear to have publicly accessible IP addresses.  The one I'm typing this from is 142.104.68.128.

**Comment by RobertLeahy** [comment]
Apparently this Mac has a public DNS name too: anitaborg.cs.uvic.ca

**Comment by RobertLeahy** [comment]
`ssh dynfu@anitaborg.cs.uvic.ca` - LARCHWOOD
`ssh dynfu@senft-mini.cs.uvic.ca` - INGLEWOOD

**Comment by jordan-heemskerk** [comment]
`ssh dynfu@noel-pc.cs.uvic.ca` - REDWOOD

**Comment by RobertLeahy** [comment]
REDWOOD has an IP of 142.104.68.193.  DNS wasn't working properly from home and I had to fallback on IP.
