### ISSUE TITLE
INGLEWOOD doesn't have El Capitan

### ISSUE THREAD

**Issue by jordan-heemskerk** [RobertLeahy/SENG499#87]
@ataiya are we good to upgrade this so it matches the other computer (LARCHWOOD)?

I think we need an Apple ID to do it. Should we use one of our personal ones, create a new one, or do you have one that you like to use.

This is causing issues with an outdated version of LLVM.

**Comment by taiya** [comment]
Yes you can go ahead and update it (you can use your own apple ID.
If there is a problem, let me know. --Andrea
