### ISSUE TITLE
LARCHWOOD GPU Insufficient

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#90]
@ataiya, LARCHWOOD's GPU is a Radeon 4850 which has beta-at-best support for OpenCL.

All of the OpenCL issues we were having on the lab machines evaporated as soon as we built on REDWOOD (which has a Radeon HD 6770M).

Among other things the 4850 (and thus LARCHWOOD) doesn't seem to support [`vstore`](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/vstoren.html) or [`vload`](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/vloadn.html) (including either of these in OpenCL source just causes the build to silently fail with nothing in the build log, building with `CL_LOG_ERRORS=stdout` gives a generic error about how the program couldn't be built for the 4850) both of which we use heavily in our kernels/programs.

Given this and notwithstanding any future developments I don't believe we'll be able to use LARCHWOOD.  We should be fine with two machines.

**Comment by taiya** [comment]
Good catch!

There is another machine by the big tv (from the tech office). You can check what version is running there. The admin account credentials are on a postit note on the back of the screen.

If you don't care about having a 3rd machine, that's ok too.

**Comment by RobertLeahy** [comment]
We have swapped that machine into where LARCHWOOD used to be.  It's El Capitan with a 6770M so that's good.

The only issue we had is that it wouldn't pick up an IP via DHCP.  We manually configured it to use LARCHWOOD's old IP (since LARCHWOOD isn't connected to the network now) and that seems to have worked, but that's only a short-term fix since once LARCHWOOD's lease expires and the DHCP server reassigns that address there'll be a conflict.

@ataiya is there someone we should talk to about this?

**Comment by taiya** [comment]
Hi, sorry for the sporadic replies, but we are running+attending the
conference.

> We have swapped that machine into where LARCHWOOD used to be. It's El
> Capitan with a 6770M so that's good.
> 
> Great.
> 
> The only issue we had is that it wouldn't pick up an IP via DHCP. We
> manually configured it to use LARCHWOOD’s old IP (since LARCHWOOD isn’t
> connected to the network now) and that seems to have worked, but that's
> only a short-term fix since once LARCHWOOD's lease expires and the DHCP
> server reassigns that address there'll be a conflict. @ataiya
> https://github.com/ataiya is there someone we should talk to about this?
> 
> You can write an email to itsupport@csc.uvic.ca, include all details of
> the machine (including MAC, OS, machine type, etc…) + the number that is
> written on the ethernet port on the wall and CC me to the message. Note a
> quicker alternative is to just use WIFI (all iMacs have it built-in).

—Andrea

**Comment by RobertLeahy** [comment]
If we use WiFi we probably can't SSH to that machine though.

**Comment by taiya** [comment]
​sure - so you can go ahead and contact itsupport

**Comment by RobertLeahy** [comment]
IT support wanted a name for the new iMac.  We decided on "DOGWOOD".

I have an e-mail in with them and expect a reply tomorrow.

**Comment by RobertLeahy** [comment]
![screen shot 2016-06-08 at 8 44 53 pm](https://cloud.githubusercontent.com/assets/648276/15918258/de8e0aaa-2db9-11e6-85f7-2495d852d593.png)

**Comment by RobertLeahy** [comment]
![screen shot 2016-06-08 at 8 45 39 pm](https://cloud.githubusercontent.com/assets/648276/15918268/f60946d6-2db9-11e6-8300-62dd87006a8a.png)

**Comment by RobertLeahy** [comment]
![screen shot 2016-06-08 at 8 48 25 pm](https://cloud.githubusercontent.com/assets/648276/15918318/5eedd806-2dba-11e6-840d-9246bcf907f4.png)
