### ISSUE TITLE
Travis CI & Mac

### ISSUE THREAD

**Issue by RobertLeahy** [RobertLeahy/SENG499#92]
Look into the possibility of adding Mac builds to Travis CI.

Complication: We have a "build matrix" for GCC versions, but Mac doesn't use GCC (Clang).

**Comment by jordan-heemskerk** [comment]
@RobertLeahy can you see what happened here: 

https://travis-ci.com/RobertLeahy/DynFu/jobs/41567846

Is clang not new enough?
