### ISSUE TITLE
Questions on Section 3.5

### ISSUE THREAD

**Issue by taiya** [RobertLeahy/SENG499#98]
Point to plane + small angle approximation (Eq. 16 is identical to Eq. 1 of Kinfu paper)
http://www.cs.princeton.edu/~smr/papers/icpstability.pdf

(not sure if it's necessary, but I'll give it to you nonetheless)
Derivative of a perspective projection, Eq. 24 here:
http://gfx.uvic.ca/teaching/registration/course_notes.pdf

**Comment by taiya** [comment]
And this is about Equation 24, if you have multiple constraints (i.e. correspondences) you can compute the NxN and NxK matrices on GPU, and then solve the linear system later on CPU:
![image](https://cloud.githubusercontent.com/assets/4480573/15841216/44082efe-2c04-11e6-9db5-a47edc4b996d.png)

**Comment by taiya** [comment]
Some example code for the Rusinkiewicz paper above:
[SparseICP_filter.zip](https://github.com/RobertLeahy/DynFu/files/301551/SparseICP_filter.zip)

**Comment by jordan-heemskerk** [comment]
I think I got this going in Eigen. See #103.

**Comment by taiya** [comment]
I just had dinner with the core kinect team, they called re-implementing Kinfu as a "right of passage" :)
